volumes:
  data:

services:
  elasticsearch:
    image: elasticsearch:8.2.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=password
    ports:
      - 9200:9200
    volumes:
      - data:/usr/share/elasticsearch/data
